#
#   Copyright 2014 Sean Bowen Trinity Lutheran Church & School Spring, TX
#
#  Luggage makefile for building a package that install authbuddy with postscript.

include /usr/local/share/luggage/luggage.make

TITLE=authbuddy
REVERSE_DOMAIN=com.trinityklein
PAYLOAD=\
	pack-usr-local-bin-authbuddy \
	pack-script-postflight
PACKAGE_VERSION=1.0